name = "screenshot-archive"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[vars]
NEXT_PUBLIC_APP_NAME = "Screenshot Archive"
NEXT_PUBLIC_APP_URL = "https://screenshot-archive.pages.dev"
R2_BUCKET_NAME = "screenshot-archive"
R2_ENDPOINT = "https://4c6a1abbc6cb19d74adb1e8251a8d5d0.r2.cloudflarestorage.com"

# Secrets (set via wrangler secret put)
# DATABASE_URL
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY
