name = "screenshot-archive"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_APP_NAME = "Screenshot Archive"
